apiVersion: v1
kind: Service 
metadata: 
  name: spring-boot-k8s
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - port: 8080 
      targetPort: 8080
      nodePort: 30001 
  type: NodePort 
  